// Code generated by MockGen. DO NOT EDIT.
// Source: core.go
//
// Generated by this command:
//
//	mockgen -source=core.go -destination=mocks/mocks.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/vas-sh/todo/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepoer is a mock of repoer interface.
type Mockrepoer struct {
	ctrl     *gomock.Controller
	recorder *MockrepoerMockRecorder
	isgomock struct{}
}

// MockrepoerMockRecorder is the mock recorder for Mockrepoer.
type MockrepoerMockRecorder struct {
	mock *Mockrepoer
}

// NewMockrepoer creates a new mock instance.
func NewMockrepoer(ctrl *gomock.Controller) *Mockrepoer {
	mock := &Mockrepoer{ctrl: ctrl}
	mock.recorder = &MockrepoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepoer) EXPECT() *MockrepoerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockrepoer) Create(ctx context.Context, res *models.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, res)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockrepoerMockRecorder) Create(ctx, res any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockrepoer)(nil).Create), ctx, res)
}

// List mocks base method.
func (m *Mockrepoer) List(ctx context.Context, userID int64) ([]models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockrepoerMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockrepoer)(nil).List), ctx, userID)
}

// Remove mocks base method.
func (m *Mockrepoer) Remove(ctx context.Context, id, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockrepoerMockRecorder) Remove(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*Mockrepoer)(nil).Remove), ctx, id, userID)
}

// ReportCompletions mocks base method.
func (m *Mockrepoer) ReportCompletions(ctx context.Context, userID int64) (models.CountCompletion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportCompletions", ctx, userID)
	ret0, _ := ret[0].(models.CountCompletion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportCompletions indicates an expected call of ReportCompletions.
func (mr *MockrepoerMockRecorder) ReportCompletions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportCompletions", reflect.TypeOf((*Mockrepoer)(nil).ReportCompletions), ctx, userID)
}

// ReportStatuses mocks base method.
func (m *Mockrepoer) ReportStatuses(ctx context.Context, userID int64) ([]models.CountStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportStatuses", ctx, userID)
	ret0, _ := ret[0].([]models.CountStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportStatuses indicates an expected call of ReportStatuses.
func (mr *MockrepoerMockRecorder) ReportStatuses(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportStatuses", reflect.TypeOf((*Mockrepoer)(nil).ReportStatuses), ctx, userID)
}

// Statuses mocks base method.
func (m *Mockrepoer) Statuses(ctx context.Context, userID, taskID int64) ([]models.TaskStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statuses", ctx, userID, taskID)
	ret0, _ := ret[0].([]models.TaskStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Statuses indicates an expected call of Statuses.
func (mr *MockrepoerMockRecorder) Statuses(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statuses", reflect.TypeOf((*Mockrepoer)(nil).Statuses), ctx, userID, taskID)
}

// Update mocks base method.
func (m *Mockrepoer) Update(ctx context.Context, body models.Task, userID, taskID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, body, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockrepoerMockRecorder) Update(ctx, body, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mockrepoer)(nil).Update), ctx, body, userID, taskID)
}
