name: Run unit tests and linter

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: download dependencies 
      run: go mod download

    - name: build
      run: go build cmd/main.go
      
    - uses: golangci/golangci-lint-action@v3
      with:
        version: v1.64.5

    - name: Run linter
      run: golangci-lint run -v -c ./.golangcli.yaml ./...

    - name: Run unit tests
      run: make unit-test