name: Run unit tests and linter

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - run: go mod download

    - run: | 
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.5
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Run linter
      run: make lint

    - name: Run unit tests
      run: make unit-test